#-------------------------------
# General Site Settings
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://meta-page.org/" # the base hostname & protocol for your site, e.g. http://example.com


#-------------------------------
# Build Settings
markdown: kramdown
permalink: /:title
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-toc

paginate: 8
paginate_path: "/blog/page/:num"


#-------------------------------
# Collections
collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /blog/:slug
  projects:
    output: true
    permalink: /projects/:slug
  videos:
    output: true
    permalink: /videos/:slug
  gallery:
    output: true
    permalink: /gallery/:slug
  canon:
    output: true
    permalink: /canon/:slug

# Pages Path
defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"
  - scope:
      path: ""
      type: "videos"
    values:
      layout: "video"
  - scope:
      path: ""
      type: "gallery"
    values:
      layout: "gallery"
  - scope: 
      path: ""
      type: "canon"
    values:
      layout: "canon"

sass:
  sass_dir: _sass
  style: compressed


# TOC
toc:
  autolink: true      # 자동으로 링크 생성
  no_toc_section_class: "no_toc" # 특정 섹션을 제외할 경우 클래스 지정
  min_level: 1        # 최소 제목 레벨 (h1)
  max_level: 6        # 최대 제목 레벨 (h6)
